"""test1

Revision ID: 3d3d117e6ea8
Revises: 2fa153690958
Create Date: 2026-08-31 00:25:29.239010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3d117e6ea8'
down_revision: Union[str, Sequence[str], None] = '2fa153690958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('test1', sa.String(), nullable=False))
    op.drop_constraint(op.f('reviews_rating_check'), 'reviews', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('reviews_rating_check'), 'reviews', 'rating >= 1 AND rating <= 5')
    op.drop_column('reviews', 'test1')
    # ### end Alembic commands ###
